"use client";

import { FileText, AlertTriangle, Scale, Ban, RefreshCw } from "lucide-react";

const terms = [
  {
    icon: AlertTriangle,
    title: "1. Acceptance of Terms",
    color: "text-amber-600",
    bg: "bg-amber-50",
    border: "border-amber-200",
    content: `By accessing and using CONAN App, you acknowledge that you have read, understood, and agree to be bound by these Terms & Conditions. If you do not agree to these terms, please discontinue use of the application immediately.

These terms apply to all users of CONAN App, including visitors, registered users, and any other persons who access or use the service.`,
  },
  {
    icon: AlertTriangle,
    title: "2. Medical Disclaimer",
    color: "text-red-600",
    bg: "bg-red-50",
    border: "border-red-200",
    content: `IMPORTANT: CONAN App is a screening and awareness tool ONLY.

• Results generated by this application are NOT a medical diagnosis
• This app does NOT replace professional medical advice, diagnosis, or treatment
• Always seek the advice of a qualified healthcare professional for any medical concerns
• Never disregard professional medical advice or delay seeking it because of results from this app
• In case of a medical emergency, contact emergency services immediately

The developers of CONAN App expressly disclaim any liability for decisions made based solely on app results.`,
  },
  {
    icon: Scale,
    title: "3. Limitation of Liability",
    color: "text-indigo-600",
    bg: "bg-indigo-50",
    border: "border-indigo-200",
    content: `To the maximum extent permitted by applicable law:

• CONAN App is provided "as is" without warranties of any kind
• The developers make no representations about the accuracy, reliability, or completeness of predictions
• We are not liable for any direct, indirect, incidental, or consequential damages arising from use of the app
• Confidence scores are model estimates and do not represent clinical certainty
• The app's predictions are based on population-level statistical models and may not apply to individual cases`,
  },
  {
    icon: FileText,
    title: "4. Permitted Use",
    color: "text-blue-600",
    bg: "bg-blue-50",
    border: "border-blue-200",
    content: `You may use CONAN App for:
• Personal health awareness and screening purposes
• Educational purposes related to lung cancer risk factors
• Academic research and study

You may NOT use CONAN App for:
• Clinical diagnosis or treatment decisions without professional consultation
• Commercial medical services
• Any purpose that violates applicable laws or regulations
• Attempting to reverse-engineer or misuse the prediction models`,
  },
  {
    icon: Ban,
    title: "5. Prohibited Activities",
    color: "text-rose-600",
    bg: "bg-rose-50",
    border: "border-rose-200",
    content: `The following activities are strictly prohibited:
• Using the app to provide medical advice to others as a professional service
• Uploading images that do not belong to you without proper authorization
• Attempting to circumvent security measures or access controls
• Using automated tools to scrape or extract data from the application
• Misrepresenting app results as official medical diagnoses`,
  },
  {
    icon: RefreshCw,
    title: "6. Changes to Terms",
    color: "text-slate-600",
    bg: "bg-slate-50",
    border: "border-slate-200",
    content: `We reserve the right to modify these Terms & Conditions at any time. Changes will be effective immediately upon posting. Continued use of the application after changes constitutes acceptance of the new terms.

Users are encouraged to review these terms periodically. The "Last Updated" date at the top of this page indicates when the most recent changes were made.`,
  },
];

export default function TermsContent() {
  return (
    <div className="space-y-6 animate-fadeIn">
      <div className="flex items-center gap-3">
        <div className="w-10 h-10 rounded-xl bg-slate-700 flex items-center justify-center">
          <FileText className="w-5 h-5 text-white" />
        </div>
        <div>
          <h1 className="text-xl font-bold text-slate-800">Terms & Conditions</h1>
          <p className="text-sm text-slate-500">Please read these terms carefully before using CONAN App</p>
        </div>
      </div>

      <div className="bg-slate-50 border border-slate-200 rounded-xl px-4 py-3">
        <p className="text-sm text-slate-600">
          <strong>Last Updated:</strong> February 2026 &nbsp;|&nbsp;
          <strong>Version:</strong> 1.0 &nbsp;|&nbsp;
          <strong>Governing Law:</strong> Republic of the Philippines
        </p>
      </div>

      <div className="bg-red-50 border border-red-200 rounded-xl px-4 py-3 flex items-start gap-2">
        <AlertTriangle className="w-4 h-4 text-red-600 flex-shrink-0 mt-0.5" />
        <p className="text-sm text-red-800 font-medium">
          CONAN App is a screening tool only and does NOT provide medical diagnoses.
          Results must not be used as a substitute for professional medical evaluation.
        </p>
      </div>

      <div className="space-y-3">
        {terms.map(({ icon: Icon, title, color, bg, border, content }) => (
          <div key={title} className={`bg-white border ${border} rounded-2xl p-5`}>
            <div className="flex items-center gap-2 mb-3">
              <div className={`w-8 h-8 rounded-lg ${bg} flex items-center justify-center`}>
                <Icon className={`w-4 h-4 ${color}`} />
              </div>
              <h2 className="text-sm font-bold text-slate-800">{title}</h2>
            </div>
            <p className="text-sm text-slate-600 leading-relaxed whitespace-pre-line">{content}</p>
          </div>
        ))}
      </div>

      <div className="bg-white border border-slate-200 rounded-2xl p-5">
        <h2 className="text-sm font-bold text-slate-800 mb-2">7. Governing Law & Jurisdiction</h2>
        <p className="text-sm text-slate-600 leading-relaxed">
          These Terms & Conditions are governed by the laws of the Republic of the Philippines.
          Any disputes arising from the use of CONAN App shall be subject to the exclusive jurisdiction
          of the courts of the Philippines. This application is developed as an academic/research project
          under Bulan High School and is not a commercial product.
        </p>
      </div>

      <div className="bg-blue-50 border border-blue-200 rounded-xl px-4 py-3">
        <p className="text-xs text-blue-800">
          By using CONAN App, you confirm that you are at least 13 years of age and have the legal
          capacity to enter into these terms. If you are using this app on behalf of a minor, you
          accept these terms on their behalf.
        </p>
      </div>
    </div>
  );
}
